sudo: required
services:
    - docker

before_install:
  - docker build -t skskumbharkar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run skskumbharkar/react-test npm test -- --coverage

after_success:
  - docker build -t skskumbharkar/multi-client ./client
  - docker build -t skskumbharkar/multi-nginx ./nginx
  - docker build -t skskumbharkar/multi-server ./server
  - docker build -t skskumbharkar/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker push skskumbharkar/multi-client
  - docker push skskumbharkar/multi-nginx
  - docker push skskumbharkar/multi-server
  - docker push skskumbharkar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-367942057072
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY