version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - "client"
      - "api"
      - "worker"
    ports:
      - '1000:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /multi-docker-containers/node_modules
      - ./server:/multi-docker-containers
    depends_on:
      - "redis"
      - "postgres"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /multi-docker-containers/node_modules
      - ./client:/multi-docker-containers
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /multi-docker-containers/node_modules
      - ./worker:/multi-docker-containers
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379